"""agregar dispositivo a recorridos

Revision ID: 14b1806c768d
Revises: c2c0652072d3
Create Date: 2026-10-06 16:56:12.288365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14b1806c768d'
down_revision: Union[str, Sequence[str], None] = 'c2c0652072d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recorridos', sa.Column('dispositivo_modelo', sa.String(length=100), nullable=True))
    op.add_column('recorridos', sa.Column('dispositivo_android', sa.String(length=20), nullable=True))
    op.add_column('recorridos', sa.Column('version_app', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recorridos', 'version_app')
    op.drop_column('recorridos', 'dispositivo_android')
    op.drop_column('recorridos', 'dispositivo_modelo')
    # ### end Alembic commands ###
