"""agregar ruta a recorridos

Revision ID: 471af1eb7197
Revises: 81829da7f0ee
Create Date: 2026-09-29 17:49:18.800163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '471af1eb7197'
down_revision: Union[str, Sequence[str], None] = '81829da7f0ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recorridos', sa.Column('ruta', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recorridos', 'ruta')
    # ### end Alembic commands ###
