"""crear tabla recorridos

Revision ID: 81829da7f0ee
Revises: 1a3fda716737
Create Date: 2026-09-27 15:34:13.418962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81829da7f0ee'
down_revision: Union[str, Sequence[str], None] = '1a3fda716737'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recorridos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('estado', sa.Enum('en_curso', 'finalizado', 'descartado', name='estado_recorrido'), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_fin', sa.DateTime(timezone=True), nullable=True),
    sa.Column('distancia_m', sa.Float(), nullable=True),
    sa.Column('duracion_s', sa.Integer(), nullable=True),
    sa.Column('velocidad_maxima_kmh', sa.Float(), nullable=True),
    sa.Column('velocidad_promedio_kmh', sa.Float(), nullable=True),
    sa.Column('lat_inicio', sa.Float(), nullable=False),
    sa.Column('lon_inicio', sa.Float(), nullable=False),
    sa.Column('lat_fin', sa.Float(), nullable=True),
    sa.Column('lon_fin', sa.Float(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("estado = 'en_curso' OR (fecha_fin IS NOT NULL AND distancia_m IS NOT NULL AND duracion_s IS NOT NULL AND velocidad_maxima_kmh IS NOT NULL AND velocidad_promedio_kmh IS NOT NULL)", name='ck_recorridos_cerrado_con_metricas'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recorridos_empresa_id'), 'recorridos', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_recorridos_usuario_id'), 'recorridos', ['usuario_id'], unique=False)
    op.create_index('uq_recorridos_usuario_en_curso', 'recorridos', ['usuario_id'], unique=True, postgresql_where=sa.text("estado = 'en_curso'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_recorridos_usuario_en_curso', table_name='recorridos', postgresql_where=sa.text("estado = 'en_curso'"))
    op.drop_index(op.f('ix_recorridos_usuario_id'), table_name='recorridos')
    op.drop_index(op.f('ix_recorridos_empresa_id'), table_name='recorridos')
    op.drop_table('recorridos')
    # ### end Alembic commands ###
    # Autogenerate no elimina los tipos enum de PostgreSQL
    sa.Enum(name='estado_recorrido').drop(op.get_bind(), checkfirst=True)
