"""crear tabla eventos y puntajes de recorridos

Revision ID: c2c0652072d3
Revises: 471af1eb7197
Create Date: 2026-10-04 02:28:58.532033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2c0652072d3'
down_revision: Union[str, Sequence[str], None] = '471af1eb7197'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eventos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recorrido_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('frenada_brusca', 'aceleracion_severa', 'giro_agresivo', 'exceso_velocidad', name='tipo_evento'), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('velocidad_kmh', sa.Float(), nullable=False),
    sa.Column('intensidad', sa.Float(), nullable=False),
    sa.Column('duracion_s', sa.Float(), nullable=True),
    sa.Column('velocidad_maxima_kmh', sa.Float(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(tipo = 'exceso_velocidad') = (duracion_s IS NOT NULL AND velocidad_maxima_kmh IS NOT NULL) AND (tipo = 'exceso_velocidad' OR (duracion_s IS NULL AND velocidad_maxima_kmh IS NULL))", name='ck_eventos_exceso_con_duracion'),
    sa.ForeignKeyConstraint(['recorrido_id'], ['recorridos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eventos_recorrido_id'), 'eventos', ['recorrido_id'], unique=False)
    op.add_column('recorridos', sa.Column('drivescore', sa.SmallInteger(), nullable=True))
    op.add_column('recorridos', sa.Column('puntaje_frenadas', sa.SmallInteger(), nullable=True))
    op.add_column('recorridos', sa.Column('puntaje_aceleraciones', sa.SmallInteger(), nullable=True))
    op.add_column('recorridos', sa.Column('puntaje_giros', sa.SmallInteger(), nullable=True))
    op.add_column('recorridos', sa.Column('puntaje_velocidad', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###
    # Autogenerate no detecta los CHECK de una tabla que ya existe
    op.create_check_constraint(
        'ck_recorridos_puntajes_0_100',
        'recorridos',
        '(drivescore IS NULL OR drivescore BETWEEN 0 AND 100)'
        ' AND (puntaje_frenadas IS NULL OR puntaje_frenadas BETWEEN 0 AND 100)'
        ' AND (puntaje_aceleraciones IS NULL OR puntaje_aceleraciones BETWEEN 0 AND 100)'
        ' AND (puntaje_giros IS NULL OR puntaje_giros BETWEEN 0 AND 100)'
        ' AND (puntaje_velocidad IS NULL OR puntaje_velocidad BETWEEN 0 AND 100)',
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint('ck_recorridos_puntajes_0_100', 'recorridos', type_='check')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recorridos', 'puntaje_velocidad')
    op.drop_column('recorridos', 'puntaje_giros')
    op.drop_column('recorridos', 'puntaje_aceleraciones')
    op.drop_column('recorridos', 'puntaje_frenadas')
    op.drop_column('recorridos', 'drivescore')
    op.drop_index(op.f('ix_eventos_recorrido_id'), table_name='eventos')
    op.drop_table('eventos')
    # ### end Alembic commands ###
    # Autogenerate no elimina los tipos enum nativos
    sa.Enum(name='tipo_evento').drop(op.get_bind(), checkfirst=True)
